name: Production CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Jq command to generate a failure scenario
        run: |
          cat hello.json | jq 'filter(.username == "John")'

      - name: Alert Keep on Pipeline Failure
        if: failure()
        run: |
          curl -X POST "http://10.126.31.171:8181/alerts/event" \
            -H "Content-Type: application/json" \
            -H "X-API-KEY: local" \
            -d '[
              {
                "id": "github-${{ github.run_id }}",
                "name": "GitHub Pipeline Failed",
                "severity": "critical",
                "repository": "${{ github.repository }}",
                "run_id": "${{ github.run_id }}",
                "status": "firing",
                "description": "Repository ${{ github.repository }} workflow run ${{ github.run_id }} failed"
              }
            ]'