name: Production CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Jq command to generate a failure scenario
        run: |
          cat hello.json | jq 'filter(.username == "John")'

      - name: Alert KeepHQ on Pipeline Failure
        if: failure()
        run: |
          curl -X POST "http://10.126.31.171:8181/alerts/event" \
          -H "Content-Type: application/json" \
          -H "X-API-KEY: local" \
          -d '[
          {
            "name": "GitHub Pipeline ID: ${{ github.run_id }}",
            "source": "github-actions",
            "description": "The GitHub Actions pipeline has failed. Please investigate the issue.",
            "repository": "${{ github.repository }}",
            "run_id": "${{ github.run_id }}",
            "severity": "critical",
            "status": "firing"
          }
          ]'